language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./build.sh

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./build.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
